-- 1. 회원 등급
CREATE TABLE member_grade (
    grade_code      VARCHAR2(2) PRIMARY KEY,
    grade_name      VARCHAR2(20) NOT NULL,
    min_point       NUMBER(10) DEFAULT 0 NOT NULL,
    discount_rate   NUMBER(5,2) DEFAULT 0
);

-- 2. 회원
CREATE TABLE members (
    member_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id        VARCHAR2(30) NOT NULL UNIQUE,
    member_name     VARCHAR2(50) NOT NULL,
    email           VARCHAR2(100) UNIQUE,
    phone           VARCHAR2(20),
    birth_date      DATE,
    gender          VARCHAR2(1),
    point           NUMBER(10) DEFAULT 0 NOT NULL,
    grade_code      VARCHAR2(2),
    city            VARCHAR2(50),
    address_detail  VARCHAR2(200),
    join_date       DATE DEFAULT SYSDATE NOT NULL,
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT fk_members_grade
        FOREIGN KEY (grade_code) REFERENCES member_grade(grade_code),
    CONSTRAINT ck_members_gender
        CHECK (gender IN ('M', 'F')),
    CONSTRAINT ck_members_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SLEEP'))
);

-- 3. 카테고리
CREATE TABLE categories (
    category_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name       VARCHAR2(50) NOT NULL,
    parent_category_id  NUMBER,
    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_category_id) REFERENCES categories(category_id)
);

-- 4. 상품
CREATE TABLE products (
    product_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id      NUMBER,
    product_name     VARCHAR2(100) NOT NULL,
    brand_name       VARCHAR2(50),
    price            NUMBER(10,2) NOT NULL,
    stock_qty        NUMBER(10) DEFAULT 0 NOT NULL,
    product_desc     VARCHAR2(500),
    created_at       DATE DEFAULT SYSDATE NOT NULL,
    status           VARCHAR2(20) DEFAULT 'SALE' NOT NULL,
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(category_id),
    CONSTRAINT ck_products_status
        CHECK (status IN ('SALE', 'STOP', 'SOLDOUT'))
);

-- 5. 주문
CREATE TABLE orders (
    order_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id         NUMBER NOT NULL,
    order_date        DATE DEFAULT SYSDATE NOT NULL,
    order_status      VARCHAR2(20) DEFAULT 'ORDERED' NOT NULL,
    shipping_city     VARCHAR2(50),
    shipping_address  VARCHAR2(200),
    total_amount      NUMBER(12,2) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_orders_member
        FOREIGN KEY (member_id) REFERENCES members(member_id),
    CONSTRAINT ck_orders_status
        CHECK (order_status IN ('ORDERED', 'PAID', 'SHIPPED', 'DONE', 'CANCEL'))
);

-- 6. 주문상세
CREATE TABLE order_items (
    order_item_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         NUMBER NOT NULL,
    product_id       NUMBER NOT NULL,
    order_price      NUMBER(10,2) NOT NULL,
    order_qty        NUMBER(10) NOT NULL,
    discount_amount  NUMBER(10,2) DEFAULT 0,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT ck_order_items_qty
        CHECK (order_qty > 0)
);

-- 7. 결제
CREATE TABLE payments (
    payment_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          NUMBER NOT NULL UNIQUE,
    payment_method    VARCHAR2(20) NOT NULL,
    payment_amount    NUMBER(12,2) NOT NULL,
    payment_date      DATE,
    payment_status    VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    approval_no       VARCHAR2(50),
    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT ck_payments_method
        CHECK (payment_method IN ('CARD', 'CASH', 'BANK', 'KAKAO', 'NAVER')),
    CONSTRAINT ck_payments_status
        CHECK (payment_status IN ('READY', 'PAID', 'CANCEL'))
);

-- 8. 부서
CREATE TABLE departments (
    dept_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name       VARCHAR2(50) NOT NULL,
    location_name   VARCHAR2(50)
);

-- 9. 사원
CREATE TABLE employees (
    emp_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id          NUMBER,
    emp_name         VARCHAR2(50) NOT NULL,
    job_name         VARCHAR2(50),
    manager_id       NUMBER,
    hire_date        DATE DEFAULT SYSDATE NOT NULL,
    retire_date      DATE,
    salary           NUMBER(10,2) NOT NULL,
    bonus            NUMBER(10,2),
    email            VARCHAR2(100),
    phone            VARCHAR2(20),
    CONSTRAINT fk_employees_dept
        FOREIGN KEY (dept_id) REFERENCES departments(dept_id),
    CONSTRAINT fk_employees_manager
        FOREIGN KEY (manager_id) REFERENCES employees(emp_id)
);

INSERT INTO member_grade (grade_code, grade_name, min_point, discount_rate) VALUES ('01', 'BRONZE', 0, 0);
INSERT INTO member_grade (grade_code, grade_name, min_point, discount_rate) VALUES ('02', 'SILVER', 1000, 3);
INSERT INTO member_grade (grade_code, grade_name, min_point, discount_rate) VALUES ('03', 'GOLD', 3000, 5);
INSERT INTO member_grade (grade_code, grade_name, min_point, discount_rate) VALUES ('04', 'VIP', 10000, 10);
commit;

INSERT INTO categories (category_name, parent_category_id) VALUES ('전자제품', NULL);
INSERT INTO categories (category_name, parent_category_id) VALUES ('패션', NULL);
INSERT INTO categories (category_name, parent_category_id) VALUES ('노트북', 1);
INSERT INTO categories (category_name, parent_category_id) VALUES ('스마트폰', 1);
INSERT INTO categories (category_name, parent_category_id) VALUES ('상의', 2);
commit;

INSERT INTO products (category_id, product_name, brand_name, price, stock_qty, product_desc, status)
VALUES (3, '그램 16', 'LG', 1700000, 10, '가벼운 노트북', 'SALE');

INSERT INTO products (category_id, product_name, brand_name, price, stock_qty, product_desc, status)
VALUES (4, '갤럭시 S25', 'SAMSUNG', 1450000, 30, '최신 스마트폰', 'SALE');

INSERT INTO products (category_id, product_name, brand_name, price, stock_qty, product_desc, status)
VALUES (5, '오버핏 셔츠', 'MUSINSA', 49000, 120, '봄 셔츠', 'SALE');

INSERT INTO products (category_id, product_name, brand_name, price, stock_qty, product_desc, status)
VALUES (3, '맥북 에어', 'APPLE', 1890000, 8, 'M 시리즈 탑재', 'SALE');
commit;

INSERT INTO members (login_id, member_name, email, phone, birth_date, gender, point, grade_code, city, address_detail, status)
VALUES ('kim01', '김상우', 'kim01@test.com', '010-1111-2222', '2000-01-10', 'M', 1200, '02', '서울', '강남구 역삼동', 'ACTIVE');

INSERT INTO members (login_id, member_name, email, phone, birth_date, gender, point, grade_code, city, address_detail, status)
VALUES ('lee02', '이수민', 'lee02@test.com', '010-2222-3333', '1999-05-21', 'F', 3500, '03', '부산', '해운대구 우동', 'ACTIVE');

INSERT INTO members (login_id, member_name, email, phone, birth_date, gender, point, grade_code, city, address_detail, status)
VALUES ('park03', '박민수', 'park03@test.com', '010-3333-4444', '2001-11-07', 'M', 200, '01', '대구', '수성구 범어동', 'SLEEP');

INSERT INTO members (login_id, member_name, email, phone, birth_date, gender, point, grade_code, city, address_detail, status)
VALUES ('choi04', '최지영', NULL, '010-4444-5555', '1998-08-15', 'F', 11000, '04', '서울', '송파구 잠실동', 'ACTIVE');
commit;

INSERT INTO departments (dept_name, location_name) VALUES ('인사부', '서울');
INSERT INTO departments (dept_name, location_name) VALUES ('영업부', '부산');
INSERT INTO departments (dept_name, location_name) VALUES ('개발부', '판교');
commit;

INSERT INTO employees (emp_id, dept_id, emp_name, job_name, manager_id, hire_date, retire_date, salary, bonus, email, phone)
VALUES (1, 1, '홍길동', 'HR_MANAGER', NULL, DATE '2020-03-01', NULL, 4200, 300, 'hong@test.com', '02-111-2222');

INSERT INTO employees (emp_id, dept_id, emp_name, job_name, manager_id, hire_date, retire_date, salary, bonus, email, phone)
VALUES (2, 2, '김영희', 'SALES', 1, DATE '2021-07-15', NULL, 3500, NULL, 'kimyh@test.com', '02-222-3333');

INSERT INTO employees (emp_id, dept_id, emp_name, job_name, manager_id, hire_date, retire_date, salary, bonus, email, phone)
VALUES (3, 3, '이철수', 'DEV', 1, DATE '2022-01-10', NULL, 5000, 500, 'lee@test.com', '02-333-4444');

COMMIT;

INSERT INTO orders (member_id, order_date, order_status, shipping_city, shipping_address, total_amount)
VALUES (1, '2026-03-01', 'PAID', '서울', '강남구 역삼동', 1749000);

INSERT INTO orders (member_id, order_date, order_status, shipping_city, shipping_address, total_amount)
VALUES (2, '2026-03-03', 'DONE', '부산', '해운대구 우동', 1450000);

INSERT INTO orders (member_id, order_date, order_status, shipping_city, shipping_address, total_amount)
VALUES (4, '2026-03-05', 'ORDERED', '서울', '송파구 잠실동', 98000);
commit;

INSERT INTO order_items (order_id, product_id, order_price, order_qty, discount_amount)
VALUES (1, 1, 1700000, 1, 0);

INSERT INTO order_items (order_id, product_id, order_price, order_qty, discount_amount)
VALUES (1, 3, 49000, 1, 0);

INSERT INTO order_items (order_id, product_id, order_price, order_qty, discount_amount)
VALUES (2, 2, 1450000, 1, 0);

INSERT INTO order_items (order_id, product_id, order_price, order_qty, discount_amount)
VALUES (3, 3, 49000, 2, 0);
commit;

INSERT INTO payments (order_id, payment_method, payment_amount, payment_date, payment_status, approval_no)
VALUES (1, 'CARD', 1749000, '2026-03-01', 'PAID', 'APPROVE-1001');

INSERT INTO payments (order_id, payment_method, payment_amount, payment_date, payment_status, approval_no)
VALUES (2, 'KAKAO', 1450000, '2026-03-03', 'PAID', 'APPROVE-1002');

INSERT INTO payments (order_id, payment_method, payment_amount, payment_date, payment_status, approval_no)
VALUES (3, 'BANK', 98000, NULL, 'READY', NULL);
commit;

